import { Car } from "./Types";

const carsData: Car[] = [
  {
    city_mpg: 22,
    class: "Sedan",
    combination_mpg: 26,
    cylinders: 4,
    displacement: 2.5,
    drive: "FWD",
    fuel_type: "Gas",
    highway_mpg: 30,
    make: "Toyota",
    model: "Camry",
    transmission: "Automatic",
    year: 2020,
  },
  {
    city_mpg: 20,
    class: "SUV",
    combination_mpg: 24,
    cylinders: 6,
    displacement: 3.5,
    drive: "AWD",
    fuel_type: "Gas",
    highway_mpg: 28,
    make: "Honda",
    model: "Pilot",
    transmission: "Automatic",
    year: 2021,
  },
  {
    city_mpg: 18,
    class: "Truck",
    combination_mpg: 20,
    cylinders: 8,
    displacement: 5.3,
    drive: "4WD",
    fuel_type: "Gas",
    highway_mpg: 22,
    make: "Chevrolet",
    model: "Silverado 1500",
    transmission: "Automatic",
    year: 2021,
  },
  {
    city_mpg: 23,
    class: "Coupe",
    combination_mpg: 26,
    cylinders: 4,
    displacement: 2.0,
    drive: "RWD",
    fuel_type: "Gas",
    highway_mpg: 30,
    make: "BMW",
    model: "4 Series",
    transmission: "Automatic",
    year: 2022,
  },
  {
    city_mpg: 25,
    class: "Hatchback",
    combination_mpg: 29,
    cylinders: 4,
    displacement: 1.8,
    drive: "FWD",
    fuel_type: "Gas",
    highway_mpg: 33,
    make: "Ford",
    model: "Focus",
    transmission: "Manual",
    year: 2019,
  },
  {
    city_mpg: 21,
    class: "Sedan",
    combination_mpg: 24,
    cylinders: 4,
    displacement: 2.0,
    drive: "FWD",
    fuel_type: "Gas",
    highway_mpg: 27,
    make: "Audi",
    model: "A4",
    transmission: "Automatic",
    year: 2020,
  },
  {
    city_mpg: 22,
    class: "SUV",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2.5,
    drive: "AWD",
    fuel_type: "Gas",
    highway_mpg: 28,
    make: "Subaru",
    model: "Outback",
    transmission: "CVT",
    year: 2021,
  },
  {
    city_mpg: 21,
    class: "SUV",
    combination_mpg: 24,
    cylinders: 6,
    displacement: 3.0,
    drive: "AWD",
    fuel_type: "Gas",
    highway_mpg: 27,
    make: "Nissan",
    model: "Murano",
    transmission: "CVT",
    year: 2020,
  },
  {
    city_mpg: 20,
    class: "Truck",
    combination_mpg: 22,
    cylinders: 6,
    displacement: 3.5,
    drive: "4WD",
    fuel_type: "Gas",
    highway_mpg: 24,
    make: "Ford",
    model: "F-150",
    transmission: "Automatic",
    year: 2022,
  },
  {
    city_mpg: 15,
    class: "Truck",
    combination_mpg: 17,
    cylinders: 8,
    displacement: 6.2,
    drive: "4WD",
    fuel_type: "Gas",
    highway_mpg: 19,
    make: "Ram",
    model: "1500",
    transmission: "Automatic",
    year: 2021,
  },
  {
    city_mpg: 18,
    class: "SUV",
    combination_mpg: 21,
    cylinders: 6,
    displacement: 3.6,
    drive: "AWD",
    fuel_type: "Gas",
    highway_mpg: 24,
    make: "Jeep",
    model: "Grand Cherokee",
    transmission: "Automatic",
    year: 2020,
  },
  {
    city_mpg: 24,
    class: "Sedan",
    combination_mpg: 28,
    cylinders: 4,
    displacement: 1.8,
    drive: "FWD",
    fuel_type: "Gas",
    highway_mpg: 32,
    make: "Honda",
    model: "Civic",
    transmission: "Manual",
    year: 2019,
  },
  {
    city_mpg: 21,
    class: "SUV",
    combination_mpg: 24,
    cylinders: 4,
    displacement: 2.0,
    drive: "AWD",
    fuel_type: "Gas",
    highway_mpg: 27,
    make: "Toyota",
    model: "RAV4",
    transmission: "CVT",
    year: 2021,
  },
  {
    city_mpg: 20,
    class: "Truck",
    combination_mpg: 22,
    cylinders: 8,
    displacement: 5.0,
    drive: "4WD",
    fuel_type: "Gas",
    highway_mpg: 23,
    make: "Toyota",
    model: "Tundra",
    transmission: "Automatic",
    year: 2020,
  },
  {
    city_mpg: 22,
    class: "Sedan",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2.4,
    drive: "FWD",
    fuel_type: "Gas",
    highway_mpg: 29,
    make: "Hyundai",
    model: "Sonata",
    transmission: "Automatic",
    year: 2021,
  },
  {
    city_mpg: 19,
    class: "SUV",
    combination_mpg: 23,
    cylinders: 6,
    displacement: 3.6,
    drive: "AWD",
    fuel_type: "Gas",
    highway_mpg: 26,
    make: "GMC",
    model: "Acadia",
    transmission: "Automatic",
    year: 2020,
  },
  {
    city_mpg: 20,
    class: "Truck",
    combination_mpg: 23,
    cylinders: 6,
    displacement: 2.7,
    drive: "4WD",
    fuel_type: "Gas",
    highway_mpg: 25,
    make: "Ford",
    model: "Ranger",
    transmission: "Automatic",
    year: 2021,
  },
  {
    city_mpg: 21,
    class: "Sedan",
    combination_mpg: 24,
    cylinders: 4,
    displacement: 2.5,
    drive: "FWD",
    fuel_type: "Gas",
    highway_mpg: 28,
    make: "Mazda",
    model: "6",
    transmission: "Automatic",
    year: 2020,
  },
  {
    city_mpg: 24,
    class: "Hatchback",
    combination_mpg: 27,
    cylinders: 4,
    displacement: 2.0,
    drive: "FWD",
    fuel_type: "Gas",
    highway_mpg: 31,
    make: "Volkswagen",
    model: "Golf",
    transmission: "Manual",
    year: 2021,
  },
  {
    city_mpg: 21,
    class: "SUV",
    combination_mpg: 25,
    cylinders: 4,
    displacement: 2.5,
    drive: "AWD",
    fuel_type: "Gas",
    highway_mpg: 29,
    make: "Mazda",
    model: "CX-5",
    transmission: "Automatic",
    year: 2020,
  },
  {
    city_mpg: 25,
    class: "Sedan",
    combination_mpg: 28,
    cylinders: 4,
    displacement: 1.6,
    drive: "FWD",
    fuel_type: "Gas",
    highway_mpg: 32,
    make: "Kia",
    model: "Forte",
    transmission: "Automatic",
    year: 2021,
  },
  {
    city_mpg: 124,
    class: "Sedan",
    combination_mpg: 120,
    cylinders: 0,
    displacement: 0.0,
    drive: "RWD",
    fuel_type: "Electric",
    highway_mpg: 116,
    make: "Tesla",
    model: "Model 3",
    transmission: "Automatic",
    year: 2023,
  },
  {
    city_mpg: 121,
    class: "SUV",
    combination_mpg: 105,
    cylinders: 0,
    displacement: 0.0,
    drive: "AWD",
    fuel_type: "Electric",
    highway_mpg: 98,
    make: "Ford",
    model: "Mustang Mach-E",
    transmission: "Automatic",
    year: 2022,
  },
  {
    city_mpg: 132,
    class: "Hatchback",
    combination_mpg: 118,
    cylinders: 0,
    displacement: 0.0,
    drive: "FWD",
    fuel_type: "Electric",
    highway_mpg: 104,
    make: "Hyundai",
    model: "Ioniq 5",
    transmission: "Automatic",
    year: 2023,
  },
];

export default carsData;
